name: setup-rust
description: setup rust and components
inputs:
  targets:
    description: "Targets to build for"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: Swatinem/rust-cache@v2
      with:
        cache-directories: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
        key: ${{ runner.os }}-${{ inputs.targets }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.targets }}
    - name: install dinghy
      shell: bash
      run: |
        if ! cargo dinghy -V &> /dev/null; then
          cargo install cargo-dinghy
        fi
