name: setup-rust
description: setup rust and components
inputs:
  platform:
    description: "Platform to build for"
    required: true
  targets:
    description: "Targets to build for"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: Swatinem/rust-cache@v2
      with:
        cache-directories: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
        key: ${{ runner.os }}-${{ inputs.platform }}-${{ inputs.targets }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.targets }}
