name: run-tests-android
description: run tests on android

inputs:
  api-level:
    description: "API level to use"
    required: false
    default: "34"

runs:
  using: composite
  steps:
    - name: create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ inputs.api-level }}
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: |
          export ADB_DEVICE_ID=$(adb devices | sed -n '2p' | cut -f1) && \
          cargo dinghy -d ${ADB_DEVICE_ID} test
