name: rust-multiplatform

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            target: aarch64-apple-darwin
          - platform: macos-13
            target: x86_64-apple-darwin
          # - platform: linux-arm64
          #   target: aarch64-unknown-linux-gnu
          # - platform: ubuntu-latest
          #   target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
        with:
          platform: ${{ matrix.platform }}
          targets: ${{ matrix.target }}
      - run: cargo test --target ${{ matrix.target }}
      - run: cargo build --target ${{ matrix.target }}
