name: rust-multiplatform

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: winarm64
            target: aarch64-pc-windows-msvc
          # - platform: windows-latest
          #   target: x86_64-pc-windows-msvc
          # - platform: windows-latest
          #   target: aarch64-pc-windows-msvc
          # - platform: macos-latest
          #   target: aarch64-apple-darwin
          - platform: macos-latest
            target: universal-apple-darwin
          - platform: macos-latest
            target: aarch64-apple-ios
          # - platform: macos-13
          #   target: x86_64-apple-darwin
          # - platform: linux-arm64
          #   target: aarch64-unknown-linux-gnu
          # - platform: ubuntu-latest
          #   target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust-winarm64
        if: matrix.platform == 'winarm64'
      - uses: ./.github/actions/setup-rust
        if: matrix.platform != 'winarm64'
        with:
          platform: ${{ matrix.platform }}
          targets: ${{ matrix.target }}
      - run: cargo test --lib --target ${{ matrix.target }}
      - run: cargo build --target ${{ matrix.target }}
