name: simple-avd-arm

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64-v8a
            target: aarch64-linux-android
            dinghy_platform: auto-android-aarch64-api29
            api_level: 29
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
        with:
          targets: ${{ matrix.target }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api_level }}
          arch: ${{ matrix.arch }}
          target: google_apis
          script: |
            echo "Running tests"
            adb devices
            cargo dinghy --platform ${{ matrix.dinghy_platform }} -d emulator-5554 test
            echo "Tests complete"
