name: build-winarm64

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: winarm64
            target: aarch64-pc-windows-msvc
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          Invoke-WebRequest -Uri https://win.rustup.rs -OutFile rustup-init.exe
          Start-Process -FilePath .\rustup-init.exe -ArgumentList '-y' -NoNewWindow -Wait
          Remove-Item rustup-init.exe
      - name: Set up Rust environment
        run: |
          $Env:RUSTUP_HOME="$Env:USERPROFILE\.rustup"
          $Env:CARGO_HOME="$Env:USERPROFILE\.cargo"
          $Env:PATH += ";$Env:CARGO_HOME\bin"
          echo "$Env:CARGO_HOME\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          rustc --version
      - name: Run cargo test
        run: cargo test --target ${{ matrix.target }}
      - name: Run cargo build
        run: cargo build --target ${{ matrix.target }}
