name: simple-avd

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # - arch: x86
          #   target: i686-linux-android
          #   dinghy_platform: auto-android-i686-api29
          #   api_level: 29
          # - arch: x86_64
          #   target: x86_64-linux-android
          #   dinghy_platform: auto-android-x86_64-api29
          #   api_level: 29
          - arch: arm64-v8a
            target: aarch64-linux-android
            dinghy_platform: auto-android-aarch64-api29
            api_level: 29

    steps:
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls /dev/kvm
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
        with:
          targets: ${{ matrix.target }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api_level }}
          arch: ${{ matrix.arch }}
          target: google_apis
          script: |
            echo "Running tests"
            adb devices
            cargo dinghy --platform ${{ matrix.dinghy_platform }} -d emulator-5554 test
            echo "Tests complete"
